name: Push Design System Data

env:
  ZEROHEIGHT_CLIENT_ID: "${{ secrets.ZEROHEIGHT_CLIENT_ID }}"
  ZEROHEIGHT_ACCESS_TOKEN: "${{ secrets.ZEROHEIGHT_ACCESS_TOKEN }}"

run-name: 📊 Analyze and push design system adoption data to zeroheight
on: [push]
jobs:
  analyze:
    runs-on: ubuntu-latest
    steps:
      - name: Start
        uses: actions/setup-node@v3
        with:
          node-version: "20"
        run: |
          echo "🚀 Analyzing adoption data and pushing to zeroheight"
          npx @zeroheight/adoption-cli analyze --interactive false --repo-name example-airorange-app 
      - name: Complete
        run: echo "💫 Component adoption analysis complete"
